% Project 5
% CEG 7850 - Digital Image Processing
% Alex Reigle

function [] = main()
path = pwd;

% Problem 2: One-Dimensional Discrete Wavelet Transforms
% Using the function f(x) = {1, 4, -3, 0} from example 7.19 (pg. 512)
% Write a program to compute a j-scale DWT and IDWT using Haar wavelets

f = [1, 4, -3 0];

[j1_DWT_1D, j1_iDWT_1D] = haarWavelet1D(f,1);
[j2_DWT_1D, j2_iDWT_1D] = haarWavelet1D(f,2);
[j3_DWT_1D, j3_iDWT_1D] = haarWavelet1D(f,3);
[j4_DWT_1D, j4_iDWT_1D] = haarWavelet1D(f,4);

msgbox({'Scale:';['J=1','  DWT: ', num2str(j1_DWT_1D)]; ...
                 ['J=2','  DWT: ', num2str(j2_DWT_1D)]; ...
                 ['J=3','  DWT: ', num2str(j3_DWT_1D)]; ...
                 ['J=4','  DWT: ', num2str(j4_DWT_1D)]; '';...
        'All iDWT are equal.'; ['iDWT: ', num2str(j1_iDWT_1D)]}, 'Problem 1 Solution');

% Problem 3: Two-Dimensional Wavelet Transforms
% Preform a 2D j-scale (j = 1,2,3) DWT and iDWT on the image from Figure
% 7.30a  to recreate fig. 7.30(a-d) (pg. 523) from the text book.

im6_30aVase_path = [path, filesep, 'F6_30(a)(Vase).tif'];
im6_30aVase = imread(im6_30aVase_path);

im6_30aVase = cast(im6_30aVase, 'double');

[j1_DWT_2D, j1_vDWT, j1_hDWT, j1_dDWT, j1_iDWT_2D] = haarWavelet2D(im6_30aVase,1);
[j2_DWT_2D, j2_vDWT, j2_hDWT, j2_dDWT, j2_iDWT_2D] = haarWavelet2D(im6_30aVase,2);
[j3_DWT_2D, j3_vDWT, j3_hDWT, j3_dDWT, j3_iDWT_2D] = haarWavelet2D(im6_30aVase,3);

% This figure will show the reconstructed 2D-DWT approximatation (i.e. only
% the parts of Fig. 7.30 that look like the real image)
figure(3);
subplot(2,2,1);     imshow(cast(im6_30aVase, 'uint8'));   title('Original Image');
subplot(2,2,2);     imshow(cast(j1_DWT_2D, 'uint8'));     title('One-Scale Haar 2D-DWT');
subplot(2,2,3);     imshow(cast(j2_DWT_2D, 'uint8'));     title('Two-Scale Haar 2D-DWT');
subplot(2,2,4);     imshow(cast(j3_DWT_2D, 'uint8'));     title('Three-Scale Haar 2D-DWT');

% This is a direct recreatation of Fig. 7.30 from the text.
im7_30a = im6_30aVase;

im7_30b = im7_30a;
im7_30b(257:end,1:256)   = j1_vDWT;
im7_30b(1:256,257:end)   = j1_hDWT;
im7_30b(257:end,257:end) = j1_dDWT;
im7_30b(1:256,1:256)     = j1_DWT_2D;

im7_30c = im7_30b;
im7_30c(129:256,1:128)   = j2_vDWT;
im7_30c(1:128,129:256)   = j2_hDWT;
im7_30c(129:256,129:256) = j2_dDWT;
im7_30c(1:128,1:128)     = j2_DWT_2D;

im7_30d = im7_30c;
im7_30d(65:128,1:64)     = j3_vDWT;
im7_30d(1:64,65:128)     = j3_hDWT;
im7_30d(65:128,65:128)   = j3_dDWT;
im7_30d(1:64,1:64)       = j3_DWT_2D;

im7_30b = quantize(im7_30b);
im7_30c = quantize(im7_30c);
im7_30d = quantize(im7_30d);

im7_30b(1:256,1:256)     = j1_DWT_2D;
im7_30c(1:128,1:128)     = j2_DWT_2D;
im7_30d(1:64,1:64)       = j3_DWT_2D;

figure(31);
subplot(2,2,1);     imshow(cast(im7_30a, 'uint8'));   title('Original Image');
subplot(2,2,2);     imshow(cast(im7_30b, 'uint8'));   title('One-Scale Haar 2D-DWT');
subplot(2,2,3);     imshow(cast(im7_30c, 'uint8'));   title('Two-Scale Haar 2D-DWT');
subplot(2,2,4);     imshow(cast(im7_30d, 'uint8'));   title('Three-Scale Haar 2D-DWT');

% Problem 4: Wavelet Transform Modifications
% Reduce image 4.40a to 512x512 pixels.
im4_40a_path = [path, filesep, 'Fig0440(a)(testpattern) (1).tif'];
im4_40a = imread(im4_40a_path);

temp = zeros(512,512);
for i = 1:size(temp,1)
    for ii = 1:size(temp,2)
        temp(i,ii) = im4_40a(2*i, 2*ii);
    end
end
im4_40a = temp;

% (a) Zero the approximation coefficients generated by 2D Harr DWT and
%     reconstruct the image to note the differences
[p4a_j1_apprDWT, p4a_j1_vertDWT, p4a_j1_horzDWT, p4a_j1_diagDWT, p4a_j1_iDWT] = haarWavelet2D(im4_40a, 1);
    p4a_j1_zReconst = idwt2(0.*p4a_j1_apprDWT, p4a_j1_vertDWT, p4a_j1_horzDWT, p4a_j1_diagDWT, 'haar');

[p4a_j2_apprDWT, p4a_j2_vertDWT, p4a_j2_horzDWT, p4a_j2_diagDWT, p4a_j2_iDWT] = haarWavelet2D(im4_40a, 2);
    p4a_j2_zReconst = idwt2(0.*p4a_j2_apprDWT, p4a_j2_vertDWT, p4a_j2_horzDWT, p4a_j2_diagDWT, 'haar');

[p4a_j3_apprDWT, p4a_j3_vertDWT, p4a_j3_horzDWT, p4a_j3_diagDWT, p4a_j3_iDWT] = haarWavelet2D(im4_40a, 3);
    p4a_j3_zReconst = idwt2(0.*p4a_j3_apprDWT, p4a_j3_vertDWT, p4a_j3_horzDWT, p4a_j3_diagDWT, 'haar');

[p4a_j4_apprDWT, p4a_j4_vertDWT, p4a_j4_horzDWT, p4a_j4_diagDWT, p4a_j4_iDWT] = haarWavelet2D(im4_40a, 4);
    p4a_j4_zReconst = idwt2(0.*p4a_j4_apprDWT, p4a_j4_vertDWT, p4a_j4_horzDWT, p4a_j4_diagDWT, 'haar');

[p4a_j5_apprDWT, p4a_j5_vertDWT, p4a_j5_horzDWT, p4a_j5_diagDWT, p4a_j5_iDWT] = haarWavelet2D(im4_40a, 5);
    p4a_j5_zReconst = idwt2(0.*p4a_j5_apprDWT, p4a_j5_vertDWT, p4a_j5_horzDWT, p4a_j5_diagDWT, 'haar');

[p4a_j6_apprDWT, p4a_j6_vertDWT, p4a_j6_horzDWT, p4a_j6_diagDWT, p4a_j6_iDWT] = haarWavelet2D(im4_40a, 6);
    p4a_j6_zReconst = idwt2(0.*p4a_j6_apprDWT, p4a_j6_vertDWT, p4a_j6_horzDWT, p4a_j6_diagDWT, 'haar');

[p4a_j7_apprDWT, p4a_j7_vertDWT, p4a_j7_horzDWT, p4a_j7_diagDWT, p4a_j7_iDWT] = haarWavelet2D(im4_40a, 7);
    p4a_j7_zReconst = idwt2(0.*p4a_j7_apprDWT, p4a_j7_vertDWT, p4a_j7_horzDWT, p4a_j7_diagDWT, 'haar');

[p4a_j8_apprDWT, p4a_j8_vertDWT, p4a_j8_horzDWT, p4a_j8_diagDWT, p4a_j8_iDWT] = haarWavelet2D(im4_40a, 8);
    p4a_j8_zReconst = idwt2(0.*p4a_j8_apprDWT, p4a_j8_vertDWT, p4a_j8_horzDWT, p4a_j8_diagDWT, 'haar');

[p4a_j9_apprDWT, p4a_j9_vertDWT, p4a_j9_horzDWT, p4a_j9_diagDWT, p4a_j9_iDWT] = haarWavelet2D(im4_40a, 9);
    p4a_j9_zReconst = idwt2(0.*p4a_j9_apprDWT, p4a_j9_vertDWT, p4a_j9_horzDWT, p4a_j9_diagDWT, 'haar');

figure(41);
subplot(3,3,1); imshow(cast(p4a_j1_zReconst, 'uint8')); title('P4(a): J=1');
subplot(3,3,2); imshow(cast(p4a_j2_zReconst, 'uint8')); title('P4(a): J=2');
subplot(3,3,3); imshow(cast(p4a_j3_zReconst, 'uint8')); title('P4(a): J=3');
subplot(3,3,4); imshow(cast(p4a_j4_zReconst, 'uint8')); title('P4(a): J=4');
subplot(3,3,5); imshow(cast(p4a_j5_zReconst, 'uint8')); title('P4(a): J=5');
subplot(3,3,6); imshow(cast(p4a_j6_zReconst, 'uint8')); title('P4(a): J=6');
subplot(3,3,7); imshow(cast(p4a_j7_zReconst, 'uint8')); title('P4(a): J=7');
subplot(3,3,8); imshow(cast(p4a_j8_zReconst, 'uint8')); title('P4(a): J=8');
subplot(3,3,9); imshow(cast(p4a_j9_zReconst, 'uint8')); title('P4(a): J=9');

% (b) Zero the horizontal coefficients generated by 2D Harr DWT and
%     reconstruct the image to note the differences
[p4b_j1_apprDWT, p4b_j1_vertDWT, p4b_j1_horzDWT, p4b_j1_diagDWT, p4b_j1_iDWT] = haarWavelet2D(im4_40a, 1);
    p4b_j1_zReconst = idwt2(p4b_j1_apprDWT, 0.*p4b_j1_vertDWT, p4b_j1_horzDWT, p4b_j1_diagDWT, 'haar');

[p4b_j2_apprDWT, p4b_j2_vertDWT, p4b_j2_horzDWT, p4b_j2_diagDWT, p4b_j2_iDWT] = haarWavelet2D(im4_40a, 2);
    p4b_j2_zReconst = idwt2(p4b_j2_apprDWT, 0.*p4b_j2_vertDWT, p4b_j2_horzDWT, p4b_j2_diagDWT, 'haar');

[p4b_j3_apprDWT, p4b_j3_vertDWT, p4b_j3_horzDWT, p4b_j3_diagDWT, p4b_j3_iDWT] = haarWavelet2D(im4_40a, 3);
    p4b_j3_zReconst = idwt2(p4b_j3_apprDWT, 0.*p4b_j3_vertDWT, p4b_j3_horzDWT, p4b_j3_diagDWT, 'haar');

[p4b_j4_apprDWT, p4b_j4_vertDWT, p4b_j4_horzDWT, p4b_j4_diagDWT, p4b_j4_iDWT] = haarWavelet2D(im4_40a, 4);
    p4b_j4_zReconst = idwt2(p4b_j4_apprDWT, 0.*p4b_j4_vertDWT, p4b_j4_horzDWT, p4b_j4_diagDWT, 'haar');

[p4b_j5_apprDWT, p4b_j5_vertDWT, p4b_j5_horzDWT, p4b_j5_diagDWT, p4b_j5_iDWT] = haarWavelet2D(im4_40a, 5);
    p4b_j5_zReconst = idwt2(p4b_j5_apprDWT, 0.*p4b_j5_vertDWT, p4b_j5_horzDWT, p4b_j5_diagDWT, 'haar');

[p4b_j6_apprDWT, p4b_j6_vertDWT, p4b_j6_horzDWT, p4b_j6_diagDWT, p4b_j6_iDWT] = haarWavelet2D(im4_40a, 6);
    p4b_j6_zReconst = idwt2(p4b_j6_apprDWT, 0.*p4b_j6_vertDWT, p4b_j6_horzDWT, p4b_j6_diagDWT, 'haar');

[p4b_j7_apprDWT, p4b_j7_vertDWT, p4b_j7_horzDWT, p4b_j7_diagDWT, p4b_j7_iDWT] = haarWavelet2D(im4_40a, 7);
    p4b_j7_zReconst = idwt2(p4b_j7_apprDWT, 0.*p4b_j7_vertDWT, p4b_j7_horzDWT, p4b_j7_diagDWT, 'haar');

[p4b_j8_apprDWT, p4b_j8_vertDWT, p4b_j8_horzDWT, p4b_j8_diagDWT, p4b_j8_iDWT] = haarWavelet2D(im4_40a, 8);
    p4b_j8_zReconst = idwt2(p4b_j8_apprDWT, 0.*p4b_j8_vertDWT, p4b_j8_horzDWT, p4b_j8_diagDWT, 'haar');

[p4b_j9_apprDWT, p4b_j9_vertDWT, p4b_j9_horzDWT, p4b_j9_diagDWT, p4b_j9_iDWT] = haarWavelet2D(im4_40a, 9);
    p4b_j9_zReconst = idwt2(p4b_j9_apprDWT, 0.*p4b_j9_vertDWT, p4b_j9_horzDWT, p4b_j9_diagDWT, 'haar');

figure(42);
subplot(3,3,1); imshow(cast(p4b_j1_zReconst, 'uint8')); title('P4(b): J=1');
subplot(3,3,2); imshow(cast(p4b_j2_zReconst, 'uint8')); title('P4(b): J=2');
subplot(3,3,3); imshow(cast(p4b_j3_zReconst, 'uint8')); title('P4(b): J=3');
subplot(3,3,4); imshow(cast(p4b_j4_zReconst, 'uint8')); title('P4(b): J=4');
subplot(3,3,5); imshow(cast(p4b_j5_zReconst, 'uint8')); title('P4(b): J=5');
subplot(3,3,6); imshow(cast(p4b_j6_zReconst, 'uint8')); title('P4(b): J=6');
subplot(3,3,7); imshow(cast(p4b_j7_zReconst, 'uint8')); title('P4(b): J=7');
subplot(3,3,8); imshow(cast(p4b_j8_zReconst, 'uint8')); title('P4(b): J=8');
subplot(3,3,9); imshow(cast(p4b_j9_zReconst, 'uint8')); title('P4(b): J=9');

% (c) Zero the vertical coefficients generated by 2D Harr DWT and
%     reconstruct the image to note the differences
[p4c_j1_apprDWT, p4c_j1_vertDWT, p4c_j1_horzDWT, p4c_j1_diagDWT, p4c_j1_iDWT] = haarWavelet2D(im4_40a, 1);
    p4c_j1_zReconst = idwt2(p4c_j1_apprDWT, 0.*p4c_j1_vertDWT, p4c_j1_horzDWT, p4c_j1_diagDWT, 'haar');

[p4c_j2_apprDWT, p4c_j2_vertDWT, p4c_j2_horzDWT, p4c_j2_diagDWT, p4c_j2_iDWT] = haarWavelet2D(im4_40a, 2);
    p4c_j2_zReconst = idwt2(p4c_j2_apprDWT, 0.*p4c_j2_vertDWT, p4c_j2_horzDWT, p4c_j2_diagDWT, 'haar');

[p4c_j3_apprDWT, p4c_j3_vertDWT, p4c_j3_horzDWT, p4c_j3_diagDWT, p4c_j3_iDWT] = haarWavelet2D(im4_40a, 3);
    p4c_j3_zReconst = idwt2(p4c_j3_apprDWT, 0.*p4c_j3_vertDWT, p4c_j3_horzDWT, p4c_j3_diagDWT, 'haar');

[p4c_j4_apprDWT, p4c_j4_vertDWT, p4c_j4_horzDWT, p4c_j4_diagDWT, p4c_j4_iDWT] = haarWavelet2D(im4_40a, 4);
    p4c_j4_zReconst = idwt2(p4c_j4_apprDWT, 0.*p4c_j4_vertDWT, p4c_j4_horzDWT, p4c_j4_diagDWT, 'haar');

[p4c_j5_apprDWT, p4c_j5_vertDWT, p4c_j5_horzDWT, p4c_j5_diagDWT, p4c_j5_iDWT] = haarWavelet2D(im4_40a, 5);
    p4c_j5_zReconst = idwt2(p4c_j5_apprDWT, 0.*p4c_j5_vertDWT, p4c_j5_horzDWT, p4c_j5_diagDWT, 'haar');

[p4c_j6_apprDWT, p4c_j6_vertDWT, p4c_j6_horzDWT, p4c_j6_diagDWT, p4c_j6_iDWT] = haarWavelet2D(im4_40a, 6);
    p4c_j6_zReconst = idwt2(p4c_j6_apprDWT, 0.*p4c_j6_vertDWT, p4c_j6_horzDWT, p4c_j6_diagDWT, 'haar');

[p4c_j7_apprDWT, p4c_j7_vertDWT, p4c_j7_horzDWT, p4c_j7_diagDWT, p4c_j7_iDWT] = haarWavelet2D(im4_40a, 7);
    p4c_j7_zReconst = idwt2(p4c_j7_apprDWT, 0.*p4c_j7_vertDWT, p4c_j7_horzDWT, p4c_j7_diagDWT, 'haar');

[p4c_j8_apprDWT, p4c_j8_vertDWT, p4c_j8_horzDWT, p4c_j8_diagDWT, p4c_j8_iDWT] = haarWavelet2D(im4_40a, 8);
    p4c_j8_zReconst = idwt2(p4c_j8_apprDWT, 0.*p4c_j8_vertDWT, p4c_j8_horzDWT, p4c_j8_diagDWT, 'haar');

[p4c_j9_apprDWT, p4c_j9_vertDWT, p4c_j9_horzDWT, p4c_j9_diagDWT, p4c_j9_iDWT] = haarWavelet2D(im4_40a, 9);
    p4c_j9_zReconst = idwt2(p4c_j9_apprDWT, 0.*p4c_j9_vertDWT, p4c_j9_horzDWT, p4c_j9_diagDWT, 'haar');

figure(43);
subplot(3,3,1); imshow(cast(p4c_j1_zReconst, 'uint8')); title('P4(c): J=1');
subplot(3,3,2); imshow(cast(p4c_j2_zReconst, 'uint8')); title('P4(c): J=2');
subplot(3,3,3); imshow(cast(p4c_j3_zReconst, 'uint8')); title('P4(c): J=3');
subplot(3,3,4); imshow(cast(p4c_j4_zReconst, 'uint8')); title('P4(c): J=4');
subplot(3,3,5); imshow(cast(p4c_j5_zReconst, 'uint8')); title('P4(c): J=5');
subplot(3,3,6); imshow(cast(p4c_j6_zReconst, 'uint8')); title('P4(c): J=6');
subplot(3,3,7); imshow(cast(p4c_j7_zReconst, 'uint8')); title('P4(c): J=7');
subplot(3,3,8); imshow(cast(p4c_j8_zReconst, 'uint8')); title('P4(c): J=8');
subplot(3,3,9); imshow(cast(p4c_j9_zReconst, 'uint8')); title('P4(c): J=9');

% (d) Zero both the horizontal and vertical coefficients generated by 2D 
%     Harr DWT and reconstruct the image to note the differences
[p4d_j1_apprDWT, p4d_j1_vertDWT, p4d_j1_horzDWT, p4d_j1_diagDWT, p4d_j1_iDWT] = haarWavelet2D(im4_40a, 1);
    p4d_j1_zReconst = idwt2(p4d_j1_apprDWT, 0.*p4d_j1_vertDWT, p4d_j1_horzDWT, p4d_j1_diagDWT, 'haar');

[p4d_j2_apprDWT, p4d_j2_vertDWT, p4d_j2_horzDWT, p4d_j2_diagDWT, p4d_j2_iDWT] = haarWavelet2D(im4_40a, 2);
    p4d_j2_zReconst = idwt2(p4d_j2_apprDWT, 0.*p4d_j2_vertDWT, p4d_j2_horzDWT, p4d_j2_diagDWT, 'haar');

[p4d_j3_apprDWT, p4d_j3_vertDWT, p4d_j3_horzDWT, p4d_j3_diagDWT, p4d_j3_iDWT] = haarWavelet2D(im4_40a, 3);
    p4d_j3_zReconst = idwt2(p4d_j3_apprDWT, 0.*p4d_j3_vertDWT, p4d_j3_horzDWT, p4d_j3_diagDWT, 'haar');

[p4d_j4_apprDWT, p4d_j4_vertDWT, p4d_j4_horzDWT, p4d_j4_diagDWT, p4d_j4_iDWT] = haarWavelet2D(im4_40a, 4);
    p4d_j4_zReconst = idwt2(p4d_j4_apprDWT, 0.*p4d_j4_vertDWT, p4d_j4_horzDWT, p4d_j4_diagDWT, 'haar');

[p4d_j5_apprDWT, p4d_j5_vertDWT, p4d_j5_horzDWT, p4d_j5_diagDWT, p4d_j5_iDWT] = haarWavelet2D(im4_40a, 5);
    p4d_j5_zReconst = idwt2(p4d_j5_apprDWT, 0.*p4d_j5_vertDWT, p4d_j5_horzDWT, p4d_j5_diagDWT, 'haar');

[p4d_j6_apprDWT, p4d_j6_vertDWT, p4d_j6_horzDWT, p4d_j6_diagDWT, p4d_j6_iDWT] = haarWavelet2D(im4_40a, 6);
    p4d_j6_zReconst = idwt2(p4d_j6_apprDWT, 0.*p4d_j6_vertDWT, p4d_j6_horzDWT, p4d_j6_diagDWT, 'haar');

[p4d_j7_apprDWT, p4d_j7_vertDWT, p4d_j7_horzDWT, p4d_j7_diagDWT, p4d_j7_iDWT] = haarWavelet2D(im4_40a, 7);
    p4d_j7_zReconst = idwt2(p4d_j7_apprDWT, 0.*p4d_j7_vertDWT, p4d_j7_horzDWT, p4d_j7_diagDWT, 'haar');

[p4d_j8_apprDWT, p4d_j8_vertDWT, p4d_j8_horzDWT, p4d_j8_diagDWT, p4d_j8_iDWT] = haarWavelet2D(im4_40a, 8);
    p4d_j8_zReconst = idwt2(p4d_j8_apprDWT, 0.*p4d_j8_vertDWT, p4d_j8_horzDWT, p4d_j8_diagDWT, 'haar');

[p4d_j9_apprDWT, p4d_j9_vertDWT, p4d_j9_horzDWT, p4d_j9_diagDWT, p4d_j9_iDWT] = haarWavelet2D(im4_40a, 9);
    p4d_j9_zReconst = idwt2(p4d_j9_apprDWT, 0.*p4d_j9_vertDWT, p4d_j9_horzDWT, p4d_j9_diagDWT, 'haar');

figure(44);
subplot(3,3,1); imshow(cast(p4d_j1_zReconst, 'uint8')); title('P4(d): J=1');
subplot(3,3,2); imshow(cast(p4d_j2_zReconst, 'uint8')); title('P4(d): J=2');
subplot(3,3,3); imshow(cast(p4d_j3_zReconst, 'uint8')); title('P4(d): J=3');
subplot(3,3,4); imshow(cast(p4d_j4_zReconst, 'uint8')); title('P4(d): J=4');
subplot(3,3,5); imshow(cast(p4d_j5_zReconst, 'uint8')); title('P4(d): J=5');
subplot(3,3,6); imshow(cast(p4d_j6_zReconst, 'uint8')); title('P4(d): J=6');
subplot(3,3,7); imshow(cast(p4d_j7_zReconst, 'uint8')); title('P4(d): J=7');
subplot(3,3,8); imshow(cast(p4d_j8_zReconst, 'uint8')); title('P4(d): J=8');
subplot(3,3,9); imshow(cast(p4d_j9_zReconst, 'uint8')); title('P4(d): J=9');


end


function [DWT, iDWT] = haarWavelet1D(f,J)
    [DWT,l] = wavedec(f, J, 'haar');
    [iDWT]  = waverec(DWT, l, 'haar');
end

function [sApprDWT, sVertDWT, sHorzDWT, sDiagDWT, iDWT] = haarWavelet2D(image, J)
[DWT, S] = wavedec2(image, J, 'haar');
[iDWT]   = waverec2(DWT, S, 'haar');

[horzDWT, vertDWT, diagDWT] = detcoef2('all', DWT, S, J); 
apprDWT = appcoef2(DWT, S, 'haar', J);
% DWT = reshape(DWT, size(image,1), size(image,2));

imageRange = max(max(image))-min(min(image));
% scaledDWT = scalePixelValues(DWT, imageRange);
sVertDWT = scalePixelValues(vertDWT, imageRange);
sHorzDWT = scalePixelValues(horzDWT, imageRange);
sDiagDWT = scalePixelValues(diagDWT, imageRange);
sApprDWT = scalePixelValues(apprDWT, imageRange);

end

function [scaledImage] = scalePixelValues(imageProccessed, imageOrigRange)
scaledImage = zeros(size(imageProccessed,1), size(imageProccessed,2));
imageProcRange = max(max(imageProccessed)) - min(min(imageProccessed));

    for i = 1:size(imageProccessed,1)
        for j = 1:size(imageProccessed,2)
            scaledImage(i,j) = imageOrigRange*imageProccessed(i,j)/imageProcRange;
        end
    end
end  

function [imageOut] = quantize(image)
    imageOut = 0.*image;
    for i = 1:size(image,1)
        for ii = 1:size(image,2)
            if (image(i,ii) <= -68)
                imageOut(i,ii) = 0;
            elseif(image(i,ii) <= -8)
                imageOut(i,ii) = 112;
            elseif (image(i,ii) <= 32)
                imageOut(i,ii) = 128;
            elseif (image(i,ii) <= 64)
                imageOut(i,ii) = 160;
            else
                imageOut(i,ii) = 256;
            end
        end
    end
end
